clastic_alias:
    resource: "@ClasticAliasBundle/Resources/config/backoffice_routing.xml"

clastic_menu:
    resource: "@ClasticMenuBundle/Resources/config/backoffice_routing.xml"

clastic_media:
    resource: "@ClasticMediaBundle/Resources/config/backoffice_routing.xml"

clastic_taxonomy:
    resource: "@ClasticTaxonomyBundle/Resources/config/backoffice_routing.xml"

clastic_block:
    resource: "@ClasticBlockBundle/Resources/config/backoffice_routing.xml"

clastic_backoffice:
    resource: "@ClasticBackofficeBundle/Resources/config/routing.xml"
